load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main_factory",
    srcs = ["main_factory.cc"],
    deps = ["//src/lib:utility"],
)


cc_binary(
    name = "main_no_factory",
    srcs = ["main_no_factory.cc"],
    deps = ["//src/lib:utility"],
)
