# cc_test(
#     name = "lpss",
#     srcs = glob(["**/*.cc"]),
#     deps = [
#         "//src/lib:dynamic_programming_lpss_lib",
#         "@com_google_googletest//:gtest_main",
#     ],
# )


cc_test(
    name = "dynamic_programming_test",
    srcs = ["dynamic_programming_test.cc"],
    deps = [
        "//src/lib/dynamic_programming:DynamicProgrammingLib",
        "@com_google_googletest//:gtest_main",
    ],
)