load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],

)

cc_binary(
    name = "string_main",
    srcs = ["string_main.cc"],

)


cc_binary(
    name = "test_main",
    srcs = ["test_main.cc"],

)

cc_binary(
    name = "copy_ellision_main",
    srcs = ["copy_ellision_main.cc"],
)

cc_binary(
    name = "test2_main",
    srcs = ["test2_main.cc"],
)

cc_binary(
    name = "move_main",
    srcs = ["move_main.cc"],
)

cc_binary(
    name = "move_so_main",
    srcs = ["move_so_main.cc"],
)

cc_binary(
    name = "rvalue_main",
    srcs = ["rvalue_main.cc"],
)


cc_binary(
    name = "test_main_modified_exam",
    srcs = ["test_main_modified_exam.cc"],
)

cc_binary(
    name = "rule_of_5_main",
    srcs = ["rule_of_5_main.cc"],
)