load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "main",
    srcs = ["main.cc"],
)

cc_binary(
    name = "main_2",
    srcs = ["main_2.cc"],
)

cc_binary(
    name = "main3",
    srcs = ["main3.cc"],
)

cc_binary(
    name = "override_new_delete",
    srcs = ["override_new_delete.cc"],
)

cc_binary(
    name = "global_new_delete",
    srcs = ["global_new_delete.cc"],
)

cc_binary(
    name = "operator_new_delete",
    srcs = ["operator_new_delete.cc"],
)

cc_binary(
    name = "stack_allocator_main",
    srcs = ["stack_allocator_main.cc"],
)

cc_binary(
    name = "pool_allocator",
    srcs = ["pool_allocator.cc"],
)

cc_binary(
    name = "override_new_delete2",
    srcs = ["override_new_delete2.cc"],
)

cc_binary(
name = "std_allocator1",
srcs = ["std_allocator1.cc"],
)