load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "template_auto",
    srcs = ["template_auto.cc"],
)

cc_binary(
    name = "if_constexpr",
    srcs = ["if_constexpr.cc"],
)

cc_binary(
    name = "structure_binding",
    srcs = ["structure_binding.cc"],
)

cc_binary(
    name = "if_init",
    srcs = ["if_init.cc"],
)

cc_binary(
    name = "file_system",
    srcs = ["file_system.cc"],
)

cc_binary(
    name = "file_system2",
    srcs = ["file_system2.cc"],
)

cc_binary(
    name = "file_system3",
    srcs = ["file_system3.cc"],
)

cc_binary(
    name = "file_system4",
    srcs = ["file_system4.cc"],
)

cc_binary(
    name = "copy_elision",
    srcs = ["copy_elision.cc"],
)

cc_binary(
    name = "no_discard",
    srcs = ["no_discard.cc"],
)

cc_binary(
    name = "optional",
    srcs = ["optional.cc"],
)

cc_binary(
    name = "memory_resources",
    srcs = ["memory_resources.cc"],
)

