load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "explicit_constructor",
    srcs = ["explicit_constructor.cc"],
    deps = ["//src/lib:SolutionLib"],
)
