load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "constructor_main",
    srcs = ["constructor_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "destructor_main",
    srcs = ["destructor_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "const_class_main",
    srcs = ["const_class_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "operator_overloading_main",
    srcs = ["operator_overloading_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


