load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "layout1",
    srcs = ["layout1.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "layout2",
    srcs = ["layout2.cc"],
    deps = ["//src/lib:SolutionLib"],
)
