load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib", "//src/lib:utility",],
)
cc_binary(
name = "find_deduced_type",
srcs = ["find_deduced_type.cc"],
)