load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "virtual",
    srcs = ["virtual.cc"],
    deps = ["//src/lib:SolutionLib"],
)