cc_test(
    name = "tests",
    srcs = glob(["**/*.cc"]),
    deps = [
        "//src/lib:SolutionLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "vector_union",
    srcs = glob(["vector_union_test.cc"]),
    deps = [
        "//src/lib:SolutionLib",
        "@googletest//:gtest_main",
    ],
)
