load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "namespace_main",
    srcs = ["namespace_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "const_class_main",
    srcs = ["const_class_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


