cc_test(
    name = "social_distance_test",
    srcs = ["social_distance_test.cc"],
    deps = [
        "//src/lib/questions:QSocialDistanceLib",
        "//src/lib:utility",
        "@googletest//:gtest_main",
    ],
)
