cc_test(
    name = "social_distance_test",
    srcs = ["social_distance_test.cc"],
    deps = [
        "//src/lib:utility",
        "//src/lib/dontsubmit/solutions:TreeLibSolution",
        "//src/lib/questions:QSocialDistanceLib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "tree_test",
    srcs = ["tree_test.cc"],
    deps = [
        "//src/lib:utility",
        "//src/dontsubmit/solutions:TreeLibSolution",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "bst_test",
    srcs = ["bst_test.cc"],
    deps = [
        "//src/lib:utility",
        # "//src/dontsubmit/solutions:TreeLibSolution",
        "@googletest//:gtest_main",
    ],
)