# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "const_param_main",
    srcs = ["const_param_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "const_class_main",
    srcs = ["const_class_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


