load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "const_param_main",
    srcs = ["const_param_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "const_class_main",
    srcs = ["const_class_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
name = "const_pointer",
srcs = ["const_pointer.cc"],
)

cc_binary(
name = "const_functions",
srcs = ["const_functions.cc"],
)