load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ConsonantVowelImbalanceLib",
    srcs = ["consonant_vowel_imbalance.cc"],
    hdrs = ["consonant_vowel_imbalance.h"],
    visibility = ["//visibility:public"],
    deps = ["//src/lib:utility"],
)
