load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "245",
    srcs = ["245.cc"],
)

cc_binary(
    name = "379",
    srcs = ["379.cc"],
)
cc_binary(
name = "388",
srcs = ["388.cc"],
)

cc_binary(
name = "33",
srcs = ["33.cc"],
)