# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "float_main",
    srcs = ["float_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "bool_main",
    srcs = ["bool_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)