load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "set_v_set_pair_e_main",
    srcs = ["set_v_set_pair_e_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "set_of_set",
    srcs = ["set_of_set.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "unordered_set_of_unordered_set",
    srcs = ["unordered_set_of_unordered_set.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "vector_of_vector",
    srcs = ["vector_of_vector.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "vector_of_set",
    srcs = ["vector_of_set.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "vector_v_vector_pair_e_main",
    srcs = ["vector_v_vector_pair_e_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "map_main",
    srcs = ["map_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "map_of_int_to_set_graph",
    srcs = ["map_of_int_to_set_graph.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "adjacency_matrix_main",
    srcs = ["adjacency_matrix_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "pointer_main",
    srcs = ["pointer_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "adjacency_vector_of_set_main",
    srcs = ["adjacency_vector_of_set_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)
