load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "fib_main",
    srcs = ["fib_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "fib_memo_main",
    srcs = ["fib_memo_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "fib_table_main",
    srcs = ["fib_table_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "lscs_main",
    srcs = ["lscs_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "lscs_memo_main",
    srcs = ["lscs_memo_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "lscs_table_main",
    srcs = ["lscs_table_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "coin_main",
    srcs = ["coin_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "coin_memo_main",
    srcs = ["coin_memo_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "coin_tab_main",
    srcs = ["coin_tab_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "knap_01_main",
    srcs = ["knap_01_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)



cc_binary(
    name = "knap_01_memo_main",
    srcs = ["knap_01_memo_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)



cc_binary(
    name = "knap_01_table_main",
    srcs = ["knap_01_table_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "lpss_main",
    srcs = ["lpss_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)