load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "if_main",
    srcs = ["if_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "switch_main",
    srcs = ["switch_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "for_main",
    srcs = ["for_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "while_main",
    srcs = ["while_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)
