load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "rand_main",
    srcs = ["rand_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "uniform_main",
    srcs = ["uniform_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "uniform_float_main",
    srcs = ["uniform_float_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "uniform_bind_main",
    srcs = ["uniform_bind_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)