# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "lambda_main",
    srcs = ["lambda_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "lambda_stl_main",
    srcs = ["lambda_stl_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)