load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "lambda_capture_init",
    srcs = ["lambda_capture_init.cc"],   
)

cc_binary(
    name = "generic_lambda",
    srcs = ["generic_lambda.cc"],   
)

cc_binary(
    name = "return_type_deduction",
    srcs = ["return_type_deduction.cc"],   
)

cc_binary(
    name = "deprecated",
    srcs = ["deprecated.cc"],   
)

cc_binary(
    name = "other",
    srcs = ["other.cc"],   
)

cc_binary(
name = "auto",
srcs = ["auto.cc"],
)