load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "vector_union_main",
    srcs = ["vector_union_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "tree_map_main",
    srcs = ["tree_map_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "std_any_main",
    srcs = ["std_any_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)
