# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "index_function_main",
    srcs = ["index_function_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "map_main",
    srcs = ["map_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "pair_main",
    srcs = ["pair_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "set_main",
    srcs = ["set_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

