
cc_test(
    name = "segment_tree_test",
    srcs = ["segment_tree_test.cc"],
    deps = [
        "//src/lib/segment_tree:SegmentTreeLib",
        "@googletest//:gtest_main",
                  "//src/lib:utility",

    ],
)