# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "unsafe_pointers_main",
    srcs = ["unsafe_pointers_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "heap_main",
    srcs = ["heap_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)