load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "distance_matrix_main",
    srcs = ["distance_matrix_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

