load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "set_insert_n_items_main",
    srcs = ["set_insert_n_items_main.cc"],
    deps = [
        "//src/lib:SolutionLib",
        "//src/lib:vector_union_lib",
    ],
)

cc_binary(
    name = "vector_union_main",
    srcs = ["vector_union_main.cc"],
    deps = [
        "//src/lib:SolutionLib",
        "//src/lib:vector_union_lib",
    ],
)
