cc_test(
    name = "graph_vector_v_vector_pair_e_test",
    srcs = ["vector_v_vector_pair_e_test.cc"],
    deps = [
        "//src/lib:graph_vector_v_vector_pair_e_lib",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "graph_adjacency_vector_of_set_test",
    srcs = ["adjacency_vector_of_set_test.cc"],
    deps = [
        "//src/lib:graph_adjacency_vector_of_set_lib",
        "@googletest//:gtest_main",
    ],
)


cc_test(
    name = "graph_adjacency_matrix_test",
    srcs = ["adjacency_matrix_test.cc"],
    deps = [
        "//src/lib:graph_adjacency_matrix_lib",
        "@googletest//:gtest_main",
    ],
)
