load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
name = "static_cast_constructor",
srcs = ["static_cast_constructor.cc"],
)

cc_binary(
name = "static_cast_inheritance",
srcs = ["static_cast_inheritance.cc"],
)