# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "vector_union_main",
    srcs = ["vector_union_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

