# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "advanced_main",
    srcs = ["advanced_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

