load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:utility"],
)

cc_binary(
name = "simple_algorithms",
srcs = ["simple_algorithms.cc"],
deps = ["//src/lib:utility"],
)
