load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [],
)

cc_binary(
    name = "constexpr",
    srcs = ["constexpr.cc"],
    deps = [],
)
cc_binary(
name = "constexpr_class",
srcs = ["constexpr_class.cc"],
)

