load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
name = "bishop_moves",
srcs = ["bishop_moves.cc"],
    deps = ["//src/lib:SolutionLib"],

)