load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "SegmentTreeLib",
    srcs = ["segment_tree.cc"],
    hdrs = ["segment_tree.h"],
    visibility = ["//visibility:public"],
    deps = ["//src/lib:utility"],
)
