load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "main2",
    srcs = ["main2.cc"],
    deps = ["//src/lib:SolutionLib"],
)

