load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
   
)

cc_binary(
    name = "unique_ptr_main",
    srcs = ["unique_ptr_main.cc"],
)

cc_binary(
    name = "shared_ptr_main",
    srcs = ["shared_ptr_main.cc"],
)

cc_binary(
    name = "shared_ptr_main_cycle",
    srcs = ["shared_ptr_main_cycle.cc"],
)


cc_binary(
    name = "stl_shared_cycle",
    srcs = ["stl_shared_cycle.cc"],
)



cc_binary(
    name = "weak_ptr_main",
    srcs = ["weak_ptr_main.cc"],
)


cc_binary(
    name = "stl_shared_weak_main",
    srcs = ["stl_shared_weak_main.cc"],
)
cc_binary(
    name = "stl_unique_main",
    srcs = ["stl_unique_main.cc"],
)

cc_binary(
name = "stl_shared_ptr_issues",
srcs = ["stl_shared_ptr_issues.cc"],
)


cc_binary(
name = "pimple",
srcs = ["pimple.cc"],
)