load("@rules_cc//cc:defs.bzl", "cc_binary")
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [],
)

cc_binary(
    name = "stack_unwinding",
    srcs = ["stack_unwinding.cc"],
    deps = [],
)

cc_binary(
    name = "std_exception",
    srcs = ["std_exception.cc"],
    deps = [],
)

cc_binary(
    name = "rtti",
    srcs = ["rtti.cc"],
    deps = [],
)


cc_binary(
    name = "custom_rtti",
    srcs = ["custom_rtti.cc"],
    deps = [],
)

