load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "DynamicProgrammingLib",
    srcs = ["dynamic_programming.cc"],
    hdrs = ["dynamic_programming.h"],
    visibility = ["//visibility:public"],
    deps = ["//src/lib:utility"],
)
