load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "BacktrackingLib",
    srcs = ["backtracking.cc"],
    hdrs = ["backtracking.h"],
    visibility = ["//visibility:public"],
    deps = ["//src/lib:utility"],
)
