cc_test(
    name = "consonant_vowel_imbalance_test",
    srcs = ["consonant_vowel_imbalance_test.cc"],
    deps = [
        "//src/lib:utility",
        "//src/lib/consonant_vowel_imbalance:ConsonantVowelImbalanceLib",
        "@googletest//:gtest_main",
    ],
)
