load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "decltype_auto",
    srcs = ["decltype_auto.cc"],
)

cc_binary(
    name = "find_deduced_type",
    srcs = ["find_deduced_type.cc"],
)
