# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "dangerous_main",
    srcs = ["dangerous_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "dynamic_arrays_main",
    srcs = ["dynamic_arrays_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


